global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "spark-master"
    metrics_path: "/metrics/master/prometheus"
    static_configs:
      - targets: ["spark-master:8080"]

  - job_name: "spark-worker"
    metrics_path: "/metrics/worker/prometheus"
    static_configs:
      - targets: ["spark-worker:8081"]

#  - job_name: "spark-thriftserver"
#    metrics_path: "/metrics"
#    static_configs:
#      - targets: ["spark-thriftserver:8081"]
